include: package:lint/analysis_options.yaml

linter:
  rules:
    avoid_single_cascade_in_expression_statements: false
    non_constant_identifier_names: false
    avoid_classes_with_only_static_members: false
    require_trailing_commas: false
    use_build_context_synchronously: false

analyzer:
  exclude:
    - "**.g.dart"
    - "**.freezed.dart"

  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error